### ISSUE TITLE
the specified key does not exist - plugin not working

### ISSUE THREAD

**Issue by Omermiz** [rundeck-plugins/aws-s3-model-source#5]
Hi, ive been trying to make this plugin work, i put a file in the bucket, resources.xml, no folder nothing, just the file in the bucket, and i configure it right.

 `2019-10-30 15:43:18,241 ERROR ExceptionCatchingResourceModelSource - [ResourceModelSource: 2.source (aws-s3-source), project: PROJECT] 
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: Error requesting Resource Model Source from S3
        at com.rundeck.plugins.aws.S3Base.getNodes(S3Base.java:132)
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport$LoadedSource.getNodes(ProjectNodeSupport.java:456)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport.getNodeSet(ProjectNodeSupport.java:138)
        at com.dtolabs.rundeck.core.common.ProjectNodeSupport$ProjectNodesSource.getNodes(ProjectNodeSupport.java:365)
        at com.dtolabs.rundeck.core.resources.ExceptionCatchingResourceModelSource.getNodes(ExceptionCatchingResourceModelSource.java:57)
        at com.dtolabs.rundeck.core.resources.ResourceModelSource$getNodes.call(Unknown Source)
        at rundeck.services.nodes.CachedProjectNodes.reloadNodeSet(CachedProjectNodes.groovy:44)
        at rundeck.services.nodes.CachedProjectNodes$reloadNodeSet.call(Unknown Source)
        at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy:290)
        at rundeck.services.NodeService$_loadNodes_closure5.doCall(NodeService.groovy)
        at sun.reflect.GeneratedMethodAccessor1160.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:412)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at com.codahale.metrics.Timer$time$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at com.codahale.metrics.Timer$time$0.call(Unknown Source)
        at org.grails.plugins.metricsweb.MetricService.withTimer(MetricService.groovy:57)
        at sun.reflect.GeneratedMethodAccessor1159.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrap.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:144)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:104)
        at rundeck.services.NodeService$_loadNodes_closure6.doCall(NodeService.groovy:297)
        at rundeck.services.NodeService$_loadNodes_closure6.doCall(NodeService.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.run(Closure.java:499)
        at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:271)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 0730549EC1B191B7; S3 Extended Request ID: 5kcpczjTUWXMB9+D57siEKvKD9HA6tZ9xtt74tqsn5bcYcumYmcBFmdV1lswixCn08IyMzHFrjw=), S3 Extended Request ID: 5kcpczjTUWXMB9+D57siEKvKD9HA6tZ9xtt74tqsn5bcYcumYmcBFmdV1lswixCn08IyMzHFrjw=
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4921)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4867)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1467)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1326)
        at com.rundeck.plugins.aws.S3Base.getFile(S3Base.java:268)
        at com.rundeck.plugins.aws.S3Base.getNodes(S3Base.java:130)`

**Comment by lightarrow** [comment]
S3 is returning the error. What ever your looking for was not in s3. 

Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist.


 Service: Amazon S3; 
Status Code: 404;
 Error Code: NoSuchKey;

**Comment by lightarrow** [comment]
bucket = bucketname
key = /path/to/file/file.xml

**Comment by fdevans** [comment]
Sorry we missed this.  If it's still a problem please open a new Issue with current Rundeck version details, and a deeper description of how this can be repeated.
